version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "badass-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ib29hj12vlkq"
s3_prefix = "badass-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CollectionIdParameter=badass-faces"

